# -*- coding: utf-8 -*-
"""KNN .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYCyb0wlUm40W9rqnquVGLiaynj9MN8h
"""

import pandas as pd

df=pd.read_csv('/content/IRIS.csv')

print(df)

df.info()

df.head()

df_new=df[df['species']!='Iris-versicolor']

print(df_new)

df_new.info()

df_new.to_csv('iris_new.csv', index=False)

print("Filtered dataset has been saved to 'iris_filtered.csv'.")

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score

df_new=pd.read_csv('/content/iris_new.csv')

X=df_new.drop